### ISSUE TITLE
Green border appearing around last menu item when clicking on any kind of indicator

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#4] opened 2017-08-14 16:23 UTC
When clicking on any of the Indicators a green box will appear around the Clock applet. This may not happen right after log in, but soon after. It is not specific to the Clock Applet either, the "last" applet in the menu will be highlighted with the green box. For example, I've seen it with the netspeed applet and others have reported it with the Dock Applet.

## Reproducing this issue

To reproduce this you will require Ubuntu MATE 17.10 daily image and use MATE Tweak to switch to the Cupertino or Contemporary layouts. All 3 themes exhibit the issue, as do all themes from `mate-themes`. The upstream bug report below include videos showing the issue:

  * https://bugs.launchpad.net/ubuntu-mate/+bug/1709013

Tagging @raveit65

**Comment by raveit65** [comment] 2017-08-17 09:39
Omg, i never saw this madness.
Let see if it is reproducible with MATE themes + Cupertino or Contemporary layouts.

**Comment by raveit65** [comment] 2017-08-19 10:27
Gtk3-inspector shows always the truth 😄 
What we see here on applets are the *outlines* with *focus* button state which is used for tabbing with the keyboard on the panel.
Sadly, opening the menu from na-tray applets with left-click can set the *focus* state from another applet.
I can reproduce this with main-menu (the single Mate menu) on fedora too, with opening/closing the menu from nm-applet and using any theme which support outlines, ie. Submarine, Menta,......
So, the issue isn't related to themes or panel-layouts ( i use fedora layout here).
The question is why opening/closing a menu in na-tray can set **focus** button state to other applets.

So, for me this looks like an issue with na-tray applet, as it can affect all different applets which use the na-tray.
...or deprecated GtkStatusIcon which got no love from gtk+ any more.
... or SNI-Support, as mate-panel is compiled with libappindicator.
Maybe it helps to compile mate-panel without it.
As i am a bit in doubt that this can only be disabled with a gsettings key.

**Comment by raveit65** [comment] 2017-08-19 11:06
It is definetly a problem with *tabbing* suport. An example.
1. Select the top panel with crtl+alt+tab
2. Select an applet with *tab* or *arrow* keys, ie. a panel launcher.
You will see a green outline on the launcher with Ambiant-Mate theme.
3. Open the network-manager-applet menu with left-click mouse.
The green outline will disappear.
4. close network-manager-applet menu and the green outline is there again.

Similar will happen if you select the desktop with crtl+alt+tab and select a desktop icon.

**Comment by raveit65** [comment] 2017-08-19 11:49
Ok, i can verify that using mate-panel-1.17.1 (without SNI-Support) has the same effect.
After re-thinking a while i don't think it is a bug as it is more a side effect of *tabbing* support.
If an applet or launcher has focus than opening a menu from a na-tray applet should taken away the focus from the applet, as the menu is focused now.
And closing the menu will drop the focus back to the applet.
Isn't that logic, isn't it ?
😄

**Comment by flexiondotorg** [comment] 2017-08-23 16:06
@raveit65 So I agree these green outlines are for assisting with making keyboard navigation easy. Therefore, can I request this border colour be change from green to a light (perhaps dotted) color?

**Comment by raveit65** [comment] 2017-08-24 07:26
Please test using doted outlines for the panel with AD.
https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/1ebeb549323ba4997ddfd9cea826e2535ac74fb3

Btw. Do you mean light=bright or light= not heavy  ?
:-)
Personal i think this makes it not easier to navigate through the panel only with the keyboard, but up to you...
If you agree i will do that for other themes, squashing commits and change commit header too.

**Comment by flexiondotorg** [comment] 2017-08-27 19:31
I've tested but can't tell the difference. I mean light as in not heavy. So I would prefer to use a grey dotted line in stead of green.

**Comment by raveit65** [comment] 2017-08-28 15:58
branch is updated + rebased.
Please test again.

**Comment by flexiondotorg** [comment] 2017-08-29 18:38
Much better and consistent with the other keyboard navigation hints. Thank you!

**Closed as completed** 2017-08-29 18:38 UTC
